import { join } from "node:path";
import { mkdir } from "node:fs/promises";
import { defineItem } from "../item.ts";
import { ACMELABS_REPOS, expandHome } from "./repo-factory.ts";

interface PluginJson {
  name: string;
  description?: string;
  version?: string;
  author?: unknown;
  homepage?: string;
}

/**
 * Generates {devDir}/ACMElabs/.claude-plugin/marketplace.json over whichever
 * plugin repos are actually cloned (selection-aware by construction — an
 * unselected repo isn't present, so it's not listed). Schema verified against
 * real marketplaces (superwhisper, claude-plugins-official) 2026-08-26:
 * relative "./<dir>" sources; metadata from each repo's plugin.json.
 */
export async function generateMarketplace(acmelabsDir: string): Promise<string[]> {
  const plugins: Record<string, unknown>[] = [];
  const included: string[] = [];
  for (const spec of ACMELABS_REPOS) {
    const dirName = spec.dest.split("/").at(-1) as string;
    const pluginJsonPath = join(acmelabsDir, dirName, ".claude-plugin", "plugin.json");
    const file = Bun.file(pluginJsonPath);
    if (!(await file.exists())) continue; // not cloned (unselected) or not a plugin (plugin-kit ok)
    const meta = (await file.json()) as PluginJson;
    plugins.push({
      name: meta.name,
      ...(meta.description ? { description: meta.description } : {}),
      ...(meta.version ? { version: meta.version } : {}),
      ...(meta.author ? { author: meta.author } : {}),
      ...(meta.homepage ? { homepage: meta.homepage } : {}),
      source: `./${dirName}`,
    });
    included.push(meta.name);
  }
  const marketplace = {
    $schema: "https://anthropic.com/claude-code/marketplace.schema.json",
    name: "ACMElabs",
    description: "Peter's local ACMElabs plugin marketplace (generated by envsetup)",
    owner: { name: "Peter Kloss", email: "pkloss@gmail.com" },
    plugins,
  };
  const outDir = join(acmelabsDir, ".claude-plugin");
  await mkdir(outDir, { recursive: true });
  await Bun.write(join(outDir, "marketplace.json"), `${JSON.stringify(marketplace, null, 2)}\n`);
  return included;
}

export const acmelabsMarketplace = defineItem({
  id: "acmelabs-marketplace",
  title: "ACMElabs plugin marketplace (generated)",
  kind: "config-only",
  // Ordered after every plugin repo; unselected ones are skipped by the
  // engine and simply won't be present.
  deps: ACMELABS_REPOS.map((r) => r.id),
  detect: async (ctx) => {
    const dir = join(expandHome(ctx.manifest.locations.devDir), "ACMElabs");
    return { installed: await Bun.file(join(dir, ".claude-plugin", "marketplace.json")).exists() };
  },
  configure: async (ctx) => {
    const dir = join(expandHome(ctx.manifest.locations.devDir), "ACMElabs");
    const included = await generateMarketplace(dir);
    ctx.log(`marketplace lists: ${included.join(", ") || "(none cloned)"}`);
  },
  verify: async (ctx) => {
    const dir = join(expandHome(ctx.manifest.locations.devDir), "ACMElabs");
    return Bun.file(join(dir, ".claude-plugin", "marketplace.json")).exists();
  },
});
