/**
 * Peter's Chrome customization defaults, captured from his machine 2026-08-26
 * (docs/PLAN.md Chrome section). Flags live in Local State (unprotected);
 * pinned toolbar actions + extension pins live in Preferences — empirically
 * verified NOT HMAC-protected (Chrome Beta launch test, 2026-08-26).
 */

export const CHROME_FLAGS: string[] = [
  "align-pdf-default-print-settings-with-html@1",
  "autofill-enable-save-and-fill@1",
  "background-resource-fetch@1",
  "bookmark-tab-group-conversion@1",
  "camera-and-microphone-elements@1",
  "canvas-draw-element@1",
  "capture-handle-for-standalone-pwas-and-iwas@1",
  "centralized-infobar-framework@1",
  "chrome-dark-neutrals-26@1",
  "collaboration-messaging@1",
  "credential-management-unified-ui@1",
  "css-grid-lanes-layout@1",
  "declarative-performance-observer@1",
  "default-search-engine-prewarm@1",
  "desktop-glow-up@1",
  "devtools-instrumentation-breakpoints@1",
  "devtools-plus-button@1",
  "devtools-protocol-monitor@1",
  "devtools-webmcp-support@1",
  "dictation@1",
  "dom-storage-sqlite@1",
  "enable-desktop-pwas-additional-windowing-controls@1",
  "enable-desktop-pwas-tab-strip-customizations@1",
  "enable-desktop-pwas-tab-strip-settings@1",
  "enable-desktop-pwas-tab-strip@1",
  "enable-devtools-deep-link-via-extensibility-api@1",
  "enable-experimental-web-platform-features",
  "enable-future-v8-vm-features@1",
  "enable-gpu-rasterization@1",
  "enable-javascript-harmony",
  "enable-mac-pwas-notification-attribution@1",
  "enable-ntp-browser-promos@1",
  "enable-parallel-downloading@1",
  "enable-resampling-scroll-events-experimental-prediction@1",
  "enable-unframed-iwa@1",
  "enable-unrestricted-usb@1",
  "enable-web-payments-experimental-features@1",
  "energy-effect-animation@1",
  "energy-effect@1",
  "extension-tab-context-menu@1",
  "extensions-menu-access-control@1",
  "glass-frame@1",
  "happy-eyeballs-v3@1",
  "idb-sqlite-backing-store@1",
  "infobar-inline-links@1",
  "menu-simplification@1",
  "native-view-host-manages-layers@1",
  "new-content-for-checkerboarded-scrolls@1",
  "notebooks@1",
  "omnibox-loom@1",
  "organizer-panel@1",
  "overscroll-effect-on-non-root-scrollers@1",
  "page-actions-migration@1",
  "password-save-update-dropdown-menu-experiment@1",
  "populate-dom-node-id-in-focused-node-details@1",
  "prerender2-cross-origin-iframes@1",
  "prerender2@1",
  "read-anything-improved-ui@1",
  "rounded-icons@1",
  "route-matching@1",
  "search-settings-update@1",
  "skills@1",
  "split-view-horizontal@1",
  "tab-group-home@1",
  "three-button-password-save-dialog@1",
  "throttle-main-thread-to-60hz@1",
  "toolbar-app-menu-label-resizing@1",
  "toolbar-glic-button-resizing@1",
  "toolbar-glow-up@1",
  "toolbar-profile-chip-resizing@1",
  "ui-debug-tools@1",
  "uno-phase-2-follow-up@1",
  "use-persistent-cache-for-code-cache@1",
  "user-media-element@1",
  "web-app-install-dialog-win-pin@1",
  "web-app-install-dialog@1",
  "web-app-install-element@1",
  "webium@2",
  "webui-refresh-2026@1",
  "webui-rounded-icons@1",
  "webui-toolbar@1"
];

export const PINNED_ACTIONS: string[] = [
  "kActionShowChromeLabs",
  "kActionTabSearch",
  "kActionCopyUrl",
  "kActionRouteMedia",
  "kActionSidePanelShowBookmarks",
  "kActionSidePanelShowHistoryCluster",
  "kActionShowDownloads",
  "kActionShowPaymentsBubbleOrPage",
  "kActionNewIncognitoWindow",
  "kActionTaskManager",
  "kActionDevTools"
];

/** Claude extension (the one pinned extension). */
export const PINNED_EXTENSIONS: string[] = ["fcoeoabgfenejglbffodgkkbkcdhcgfn"];
